// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonRepo: typeof import('./src/components/ButtonRepo.vue')['default']
    Combobox: typeof import('@headlessui/vue')['Combobox']
    ComboboxInput: typeof import('@headlessui/vue')['ComboboxInput']
    ComboboxOption: typeof import('@headlessui/vue')['ComboboxOption']
    ComboboxOptions: typeof import('@headlessui/vue')['ComboboxOptions']
    NavSideBar: typeof import('./src/components/nav/NavSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
  }
}
