// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonRepo: typeof import('./src/components/ButtonRepo.vue')['default']
    CardItem: typeof import('./src/components/home/CardItem.vue')['default']
    CuisinesCarousel: typeof import('./src/components/home/CuisinesCarousel.vue')['default']
    Ingredients: typeof import('./src/components/recipe-info/Ingredients.vue')['default']
    Instructions: typeof import('./src/components/recipe-info/Instructions.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    NavSideBar: typeof import('./src/components/nav/NavSideBar.vue')['default']
    PreferenceForm: typeof import('./src/components/home/PreferenceForm.vue')['default']
    RecipesGrid: typeof import('./src/components/home/RecipesGrid.vue')['default']
    RecipeStats: typeof import('./src/components/recipe-info/RecipeStats.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    Summary: typeof import('./src/components/recipe-info/Summary.vue')['default']
    TextLink: typeof import('./src/components/TextLink.vue')['default']
  }
}
