// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonRepo: typeof import('./src/components/ButtonRepo.vue')['default']
    LoginButton: typeof import('./src/components/LoginButton.vue')['default']
    LogoutButton: typeof import('./src/components/LogoutButton.vue')['default']
    NavBar: typeof import('./src/components/nav/NavBar.vue')['default']
    Profile: typeof import('./src/components/nav/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
